### PR TITLE
Add demo notebook 

### PR DESCRIPTION
**Pull request by sschmidt23**
I added a demo notebook that shows an example of running BPZ with the "default" HDFN prior, computes a new custom prior from our typical RAIL training data (with an included "best broad type" file also included in the PR), and also shows some plots of the prior forms, effect of the custom prior, etc...

@yanzastro if there is anything else that you think would be useful to add, let me know

### CODE REVIEW

**Comment by sschmidt23** [comment]
I added computation of the point estimate stats to the end of the notebook, along with some text about how the prior not majorly changing things is a good thing, as we do not want to be prior-dominated.  I was trying to think if it would be good to show using a different set of templates in the notebook, which would have a more dramatic effect on the results.  I have a set of like 229 SEDs that are meant to span the DC2 templates a little bit better, but I'd have to do some work to figure out a smaller subset of those SEDs that are somewhat similar the the eight CWWSB SEDs.  Also, because they contain non-physical features intrinsic to DC2, I worry a little that others might grab them and use them on real data, which would be bad.

What do you think, @yanzastro, would adding an example of using a different template set be useful in this notebook?

**Comment by sschmidt23** [comment]
I could always make a separate notebook in addition to this demo notebook that is specific to using a different set of templates, that is an option as well.

**Comment by sschmidt23** [comment]
@yanzastro I did go ahead and add a second notebook, I think it nicely shows off both how to use a custom SED set and how dramatically different the results can look.  Let me know if anything can be improved when you get a chance to review.

**Comment by yanzastro** [comment]
@sschmidt23 I just reviewed the notebooks and the content seems fine! However, the `RAIL` repo seems to have been updated very recently and some directories have their name changed. For example `rail/examples/testdata/` was changed to `rail/examples_data/testdata/`, etc. Can you check and modify the PR accordingly?

**Comment by sschmidt23** [comment]
I updated the paths here and everything now runs smoothly, so I'm going to merge this in.  Thanks for the review, Ziang!

**Pull request merged**
